Destination.create(name:"The Sun", distance: 93, gravity: 27.94, temperature: 5,505, type: "star", image_url:"")
Destination.create(name:"Jupiter", distance: 443, gravity: 2.48, temperature: -108.15, type: "planet", image_url:"")
Destination.create(name:"Saturn", distance: 876, gravity: 1.07, temperature: -178, type: "planet", image_url:"")
Destination.create(name:"Uranus", distance: 1,917, gravity: 0.89, temperature: -197.2, type: "planet", image_url:"")
Destination.create(name:"Neptune", distance: 2,797, gravity: 1.14, temperature: -201, type: "planet", image_url:"")
Destination.create(name:"Earth", distance: 0, gravity: 1, temperature: 14, type: "planet", image_url:"")
Destination.create(name:"Venus", distance: 150, gravity: 0.91, temperature: 463.85, type: "planet", image_url:"")
Destination.create(name:"Mars", distance: 211, gravity: 0.38, temperature: -63.15, type: "planet", image_url:"")
Destination.create(name:"Ganymede", distance: 390, gravity: 0.15, temperature: -163.15 type: "moon", image_url:"")
Destination.create(name:"Titan", distance: 875, gravity: 0.14, temperature: -179, type: "moon", image_url:"")
Destination.create(name:"Mercury", distance: 55, gravity: 0.38, temperature: 67, type: "planet", image_url:"")
Destination.create(name:"Callisto", distance: 390, gravity: 0.13, temperature: -133.15, type: "moon",image_url:"")
Destination.create(name:"Io", distance: 390, gravity: 0.18, temperature: -163.15, type: "moon", image_url:"")
Destination.create(name:"The Moon", distance: .24, gravity: 0.17, temperature: -23.15, type: "moon", image_url:"")
Destination.create(name:"Europa", distance: 390, gravity: 0.13, temperature: -171.15, type: "moon", image_url:"")
Destination.create(name:"Pluto", distance: 3,119, gravity: 0.06, temperature: -229.15, type: "dwarf planet", image_url:"")
Destination.create(name:"Eris", distance: 8,978, gravity: 0.08, temperature: -231.15, type: "dwarf planet", image_url:"")
Destination.create(name:"Ceres", distance: 257, gravity: 0.03, temperature: -87.15, type: "asteroid", image_url:"")
Destination.create(name:"Titania", distance: 1,692, gravity: 0.04, temperature: -198.15, type: "moon", image_url:"")
Destination.create(name:"Charon", distance: 3,119, gravity: 0.03, temperature: -220.15, type: "moon", image_url:"")